import {FC, useEffect} from "react";
import Head from 'next/head'
import {
    Main,
} from '../../components/styles/sharedstyles'

import {wrapper} from "../../redux/store";
import {fetchCurrencies} from "../../redux/slices/currencies/slice";
import Currencies from "./Currencies";


const Home:FC = ():JSX.Element => {
  return (
    <>
      <Head>
        <title>NFT Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Main>
        <Currencies />
      </Main>
    </>
  )
}

export const getStaticProps = wrapper.getStaticProps(store => async () => {
  await store.dispatch(fetchCurrencies())
  return {props: {}}
});


export default Home