import {FC} from "react";
import Head from 'next/head'
import {
    Main,
} from '../../components/styles/sharedstyles'
import Currencies from "./Currencies";

export const getStaticProps = async () => {
  const res = await fetch('https://min-api.cryptocompare.com/data/pricemultifull?fsyms=BTC&tsyms=USD,EUR')
  const data = await res.json()
  if (!data) return {notFound: true}
  return {props: {data}}
}

const Home:FC = ({data}: any):JSX.Element => {
  return (
    <>
      <Head>
        <title>NFT Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Main>
        <Currencies data={data}/>
      </Main>
    </>
  )
}



export default Home