import {FC, useEffect} from "react";
import Head from 'next/head'
import {
    Main,
} from '../../components/styles/sharedstyles'

import { wrapper} from "../../redux/store";
import {fetchCurrencies} from "../../redux/slices/currencies/slice";
import {useDispatch, useSelector} from "react-redux";
import Currencies from "./Currencies";


const Home:FC= ({initialState}: any):JSX.Element => {
  const dispatch = useDispatch()
  //
  // useEffect(() => {
  //   setInterval(() => {
  //     const fetchInterval = async () => {
  //       console.log('ffe')
  //       await dispatch(fetchCurrencies())
  //     }
  //     fetchInterval()
  //   },1000)
  // }, [])
  return (
    <>
      <Head>
        <title>NFT Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Main>
        <Currencies data={initialState.currenciesSlice.data.DISPLAY}/>
      </Main>
    </>
  )
}

export const getStaticProps = wrapper.getStaticProps(store => async () => {
  await store.dispatch(fetchCurrencies())
});


export default Home