import Link from 'next/link'
import {  Main, Title } from '../../components/styles/sharedstyles'
import Head from "next/head";

const Market = ():JSX.Element => {
  return (
    <>
      <Head>
        <title>NFT Market</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Main>
        <Title>About Page</Title>
          <Link href="/">&larr; Go Back</Link>
      </Main>
    </>
  )
}

export default Market